sudo: required

language: node_js
node_js:
  - node

services:
  - docker
  
matrix:
  include:
  - env: IMAGE=trzeci/emscripten

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src $IMAGE bash

script:
- docker exec -it emscripten emcc --version
- docker exec -it emscripten make
- cd out && node main.js
