sudo: required

language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten bash

script:
- printf '#include <iostream>\nint main() { std::cout << "HELLO WORLD!" << std::endl; return 0; }' > hello.cpp
- docker exec -it emscripten emcc --version
- docker exec -it emscripten emcc hello.cpp -o hello.js
- node hello.js
