sudo: required

language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten bash

script:
- docker exec -it emscripten emcc --version
- docker exec -it emscripten make
- node hello.js
