# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - entrypoint: /entrypoint
      - image: trzeci/emscripten:sdk-tag-1.37.18-64bit
      
    working_directory: ~/repo

    steps:
      - run:
          name: run tests
          command: |
            ls -la /
            pwd
            ls -la
            emcc --version
